### ISSUE TITLE
html export fails on second attempt

### ISSUE THREAD

**Issue by mfsbo** [gharibi/JsObjExporter#7]
**Describe the bug**
When you click on html export on example page it opens a browser print dialogue. If you cancel it and click on export button second time it gives an error in console and fails. It should open dialogue whenever export button is pressed.

**To Reproduce**
1. Go to 'https://gharibi.github.io/JsObjExporter/examples/example.html'
2. Click on 'Generate PDF under HTML to PDF'
3. A print dialogue would open with Print and Cancel options.
4. Click on Cancel
5. Click on 'Generate PDF under HTML to PDF' again
6. Open Console and see errors it would show ` Uncaught TypeError: Cannot read property 'remove' of null ` on `document.getElementById("testFrame").remove()`

**Expected behavior**
There should be no errors in console.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
I have included the js file from cdn https://www.jsdelivr.com/package/npm/object-exporter

**Comment by gharibi** [comment]
Thanks @mfsbo for resolving this issue. I updated the version and published the updated version to npm.

**Comment by mfsbo** [comment]
You are welcome. Will get npm version tomorrow. Keep up the good work.

**Comment by mfsbo** [comment]
@gharibi I think you need to generate min file in the dist folder as well or will it be automatically updated. NPM still shows min file with testFrame.

**Comment by gharibi** [comment]
Thanks for pointing it out. I republished it to npm. It should be fine in v3.4.8.
