### ISSUE TITLE
Override CSV Column Separator

### ISSUE THREAD

**Issue by mfsbo** [gharibi/JsObjExporter#9]
**Is your feature request related to a problem? Please describe.**
When you export as CSV it always export as semicolon separataed values while some programs may not want this format and want to override it with comma separated values.

**Describe the solution you'd like**
It would be good to provide an option for CSV type to include cell separator.

**Describe alternatives you've considered**
We take the data out and run a manual process on it to replace all semicolons with comma but that is not ideal

**Additional context**
None

**Comment by gharibi** [comment]
Hi @mfsbo. Thanks for using the library. I fully agree with you. There is always a debate as to whether comma or semicolon shall be used. Let's solve this by adding a property called `delimiter: <string|char>` to get the user defined separator with the default value of comma ",". How do you think?

I will endeavour to do it in the coming days.

**Comment by mfsbo** [comment]
Yes great.
It would be useful if one can set this variable to , ; or | and both headers and data is delimited by this variable.

**Comment by farrukhsubhani** [comment]
Have a look at https://github.com/farrukhsubhani/JsObjExporter/commit/96de53f51bc1e174d7d36150083e27e15b7db8ee 
I have not run it with tests just edited. You can verify and update documentation/tests etc with it.
One concern that if this new param is not optional it will break existing use of function with 3 params when people upgrade to new version. If you can make it an optional param by giving default of ‘;’ at top level call then we dont even need that if test in csv export function.

**Comment by gharibi** [comment]
Indeed we have to define a default value for this parameter in [HERE](https://github.com/gharibi/JsObjExporter/blob/master/src/js/init.js) to be backward compatible. I reckon the default shall be `,` as CSV stands for Comma Separated Values.

Initially I defined semicolon as I needed it for some projects and that's kinda wrong 😆.Feel free to open a PR, better incl. the default values. Otherwise I can also do it.

**Comment by gharibi** [comment]
There was a small typo in param and its assignment which I refactored it. I have merged your changes, updated the examples and released a new version. Thank you @farrukhsubhani.
